/**
 * The service registry keeps track of the services available for each registered
 * relation, which is how a relation can be read. Dispatch uses the registry to match
 * queries to services.
 */

#ifndef SERVICE_REGISTRY_H
#define SERVICE_REGISTRY_H

#include "btree/btree.h"
#include "kernel/operator.h"
#include "kernel/Parameter.h"
#include "kernel/Relation.h"


/**
 * A Service provides processing of a query with a given IOSignature against a
 * specific Relation, and is uniquely defined by the (Relation, IOSignature) pair.
 * A service is implemented by an Operator tree, and holds a pointer to the root
 * operator of this tree. Because an Operator assumes a specific IOSignature,
 * a pair (Relation, Operator) is also 1:1 with a Service.
 */

 enum ServiceKind {
	// A primitive service is registed by a storage provider, and evaluated by a
	// machine operator (OPERATOR_MACHINE). It does not depend on any rules or facts
	// in the knowledgebase, and is removed only when the storage is removed.
	SERVICE_PRIMITIVE = 1,
	// A compiled service is generated by the compiler and depends on a set of 
	// rules and facts, and must be invalidated if any of those rules or facts change.
	// see ServiceRegistryInvalidateTermForm().
	SERVICE_COMPILED = 2,
};

typedef struct s_Service {
	Relation const * relation;
	IOSignature ioSignature;
	// Pointer to the root of the operator sub-tree defining this service.
	Operator * op;
	enum ServiceKind kind;
} Service;

/**
 * Setup an empty service registry. Called during bootstrapping only.
 */
void SetupServiceRegistry(void);

/**
 * Create a new service wiht the given signature and Operator, adding it to
 * the service registry. Acquires a reference to both Relation.
 * Takes ownership of the operator.
 * Returns a copy of the created service.
 * 
 * NOTE: For services whose form contain repeated roles, such as `(a b b)`,
 * the signature must be unique under form permutation: for example, the two services
 * `(a 1<INT b 2<INT c 3>FLOAT)` and `(a 1<INT b 2>FLOAT c 3<INT)` have the same signature
 * under the permutation $(1, 3, 2)$  and so cannot co-exist. There is currently no check
 * for this criterion, as it would require form permutation which causes bootstrap problems.
 * DEBUG builds assert this constraint in DispatchIteratorNext().
 *
 * TODO: the Service structure is now returned by value since we cannot return pointers
 * into the B-tree storage structure (they may change over time). This is not great, since
 * the callers's copy may become invalide if the Service is deleted. We should probably
 * move to a stable storage an always return const * pointers, with an explicit contract
 * that pointers are valid until the Service is removed.
 * 
 * NOTE: kind should always be SERVICE_COMPILED, except for primitive services that are
 * created by CreateRelationTable. 
 */
Service CreateService(
	Relation const * relation, IOSignature ioSignature, Operator * op,
	enum ServiceKind kind);

/**
 * Returns true if another service depends on the given service.
 */
bool ServiceHasDependents(Service const * service);

/**
 * Remove the service identified by the given operator and relation.
 * This removes the services' operator, and recursively removes all operators
 * and services that depend on it.
 */
void RemoveService(Relation const * relation, Operator * op);

/**
 * Remove all services for the given relation.
 */
void ServiceRegistryRemoveAll(Relation const * relation);

/**
 * Deallocate the service registry. Before calling this function,
 * all services must have been removed.
 */
void FreeServiceRegistry(void);

/**
 * Total number of registered services.
 */
size32 ServiceRegistryCount(void);

/**
 * Number of registered services compiled from the rules; see ServiceKind.
 */
size32 ServiceRegistryNCompiled(void);


/**
 * Invalidate compiled services for the given term form. This is called whenever
 * a service or rule involving the term form is added or removed.
 * This function removes (1) every compiled Service for each Relation matching the given form,
 * and (2) every compiled Service that calls any services matching the term form, transitively.
 * 
 * A compiled service answers a query as the rules and the facts stood when it was compiled,
 * so a change to either has to remove the services it could affect; the next query then
 * compiles them again. Removing too much costs a compilation, removing too little gives a wrong answer.
 *
 * NOTE: this modifies the registries, so it cannot run while a query is being read: an
 * open DispatchIterator or MixedTypeRelation write-locks against modification.
 */
void ServiceRegistryInvalidateByTermForm(Atom termForm);

/**
 * Remove all compiled services from the registry.
 */
void RemoveAllCompiledServices(void);


/**
 * Iterating over services
 */
typedef struct {
	Relation const * relation;
	BTreeIterator btreeIterator;
} ServiceIterator;

/**
 * Create iterator over all services for a given relation
 */
void ServiceRegistryIterate(Relation const * relation, ServiceIterator * iterator);

bool ServiceIteratorNext(ServiceIterator * iterator);

Service const * ServiceIteratorPeekService(ServiceIterator const * iterator);

void ServiceIteratorEnd(ServiceIterator * iterator);

/**
 * Retrieve the operator of the service for the given relation and IO signature, which
 * must be filled to the relation arity.
 * If a matching service does not exist, returns 0
 */
Operator * ServiceRegistryFind(Relation const * relation, IOSignature ioSignature);

/**
 * CLAUDE: Copy some registered service evaluated by a machine operator of the given provider to
 * *service, and return true; return false if the registry holds no such service.
 *
 * This is only used by MachineService.c to finds the services it registered, without keeping a
 * record of them: removing services until this returns false unregisters the provider.
 * See FreeMachineServices() in library/MachineService.c
 */
bool ServiceRegistryFindByMachineProvider(
	MachineOperatorProvider const * provider, Service * service);

/**
 * For debugging
 */
void PrintService(Service const * service);

/**
 * Dump all tuples of the given relation.
 * Requires an associated service for enumerating all tuples.
 */
void RelationDump(Relation const * relation);

/**
 * Print a list of all registered services
 */
void ServiceRegistryDump(void);


#endif  // SERVICE_REGISTRY_H
