/**
 * The service registry keeps track of the services available for each registered
 * relation, which is how a relation can be read. Dispatch uses the registry to match
 * queries to services.
 */

#ifndef SERVICE_REGISTRY_H
#define SERVICE_REGISTRY_H

#include "btree/btree.h"
#include "kernel/operator.h"
#include "kernel/Parameter.h"
#include "kernel/Relation.h"


/**
 * A Service provides processing of a query with a given IOSignature against a
 * specific Relation, and is uniquely defined by the (Relation, IOSignature) pair.
 * A service is implemented by an Operator tree, and holds a pointer to the root
 * operator of this tree. Because an Operator assumes a specific IOSignature,
 * a pair (Relation, Operator) is also 1:1 with a Service.
 */

 enum ServiceKind {
	// A primitive service is provided by a machine operator (OPERATOR_MACHINE)
	// and does not depend on any rules or facts in the knowledgebase. It remains
	// valid as long as the machine operator is valid.
	SERVICE_PRIMITIVE = 1,
	// A compiled service is generated by the compiler and depends on a set of 
	// rules and facts, and must be invalidated if any of those rules or facts change.
	// see ServiceRegistryInvalidateTermForm().
	SERVICE_COMPILED = 2,
};

typedef struct s_Service {
	Relation const * relation;
	IOSignature ioSignature;
	// Pointer to the root of the operator tree defining this service.
	// NOTE: cannot be const * if we want to do AcquireOperator(op).
	// NOTE: not named "operator", which is a reserved word in C++
	Operator * op;
	enum ServiceKind kind;
} Service;

/**
 * Setup an empty service registry. Called during bootstrapping only.
 */
void SetupServiceRegistry(void);

/**
 * Associates an Operator with a Relation in the service registry, giving a service.
 * Acquires a reference to both Relation and the Operator. Returns a copy of the created service.
 *
 * If kind = SERVICE_COMPILED, this also records wht  root operator.
 * 
 * can be invalidated when one of them changes; see ServiceRegistryInvalidateTermForm().
 * 
 * NOTE: For services whose form contain repeated roles, such as `(a b b)`,
 * the signature must be unique under form permutation: for example, the two services
 * `(a 1<INT b 2<INT c 3>FLOAT)` and `(a 1<INT b 2>FLOAT c 3<INT)` have the same signature
 * under the permutation $(1, 3, 2)$  and so cannot co-exist. There is currently no check
 * for this criterion, as it would require form permutation which causes bootstrap problems.
 * DEBUG builds assert this constraint in DispatchIteratorNext().
 *
 * NOTE: the Service structure is returned by value since we cannot return pointers
 * into the B-tree storage structure (they may change over time).
 * The registry holds a reference to Service.operator.
 */
Service ServiceRegistryAdd(
	Relation const * relation, IOSignature ioSignature, Operator * op,
	enum ServiceKind kind);

/**
 * Dissociate the service of the given operator from a relation in the service
 * registry. Releases the reference to the operator, and the one to the relation.
 *
 * Every compiled service built on the removed one is invalidated, and so are the ones
 * built on those; see ServiceRegistryInvalidateTermForm().
 */
void ServiceRegistryRemove(Relation const * relation, Operator * op);

/**
 * Dissociate all services from the given relation in the service registry, invalidating
 * the compiled services built on them; see ServiceRegistryRemove().
 */
void ServiceRegistryRemoveAll(Relation const * relation);

/**
 * Deallocate the service registry. Before calling this function,
 * all services must have been removed.
 */
void FreeServiceRegistry(void);

/**
 * Total number of registered services.
 */
size32 ServiceRegistryCount(void);

/**
 * Number of registered services compiled from the rules; see ServiceKind.
 */
size32 ServiceRegistryNCompiled(void);


/**
 * Invalidate compiled services for the given term form. This is called whenever
 * a service or rule involving the term form is added or removed.
 * This function removes (1) every compiled Service for each Relation matching the given form,
 * and (2) every compiled Service that calls any services matching the term form, transitively.
 * 
 * A compiled service answers a query as the rules and the facts stood when it was compiled,
 * so a change to either has to remove the services it could affect; the next query then
 * compiles them again. Removing too much costs a compilation, removing too little gives a wrong answer.
 *
 * NOTE: this modifies the registries, so it cannot run while a query is being read: an
 * open DispatchIterator or MixedTypeRelation write-locks against modification.
 */
void ServiceRegistryInvalidateByTermForm(Atom termForm);

/**
 * Remove every compiled service, whatever its form; see ServiceRegistryInvalidateTermForm().
 */
void ServiceRegistryInvalidateAll(void);


/**
 * Iterating over services
 */
typedef struct {
	Relation const * relation;
	BTreeIterator btreeIterator;
} ServiceIterator;

/**
 * Create iterator over all services for a given relation
 */
void ServiceRegistryIterate(Relation const * relation, ServiceIterator * iterator);

bool ServiceIteratorNext(ServiceIterator * iterator);

Service const * ServiceIteratorPeekService(ServiceIterator const * iterator);

void ServiceIteratorEnd(ServiceIterator * iterator);

/**
 * Retrieve the operator of the service for the given relation and IO signature, which
 * must be filled to the relation arity.
 * If a matching service does not exist, returns 0
 */
Operator * ServiceRegistryFind(Relation const * relation, IOSignature ioSignature);

/**
 * Copy some registered service evaluated by a machine operator of the given provider to
 * *service, and return true; return false if the registry holds no such service.
 *
 * This is how a machine provider finds the services it registered, without keeping a
 * record of them: removing services until this returns false unregisters the provider.
 * See FreeMachineServices() in library/MachineService.c
 */
bool ServiceRegistryFindByMachineProvider(
	MachineProvider const * provider, Service * service);

/**
 * For debugging
 */
void PrintService(Service const * service);

/**
 * Dump all tuples of the given relation.
 * Requires an associated service for enumerating all tuples.
 */
void RelationDump(Relation const * relation);

/**
 * Print a list of all registered services
 */
void ServiceRegistryDump(void);


#endif  // SERVICE_REGISTRY_H
